window.screenOrientation = "sensor_landscape", 
loadLib("libs/min/laya.core.min.js"), 
loadLib("libs/min/laya.ani.min.js"), 
loadLib("libs/min/laya.html.min.js"), 
loadLib("libs/min/laya.particle.min.js"), 
loadLib("libs/min/laya.ui.min.js"), 
loadLib("libs/min/laya.d3.min.js"), 
loadLib("libs/min/domparserinone.min.js"), 
loadLib("libs/min/fx.phx.min.js"), 
loadLib("libs/min/laya.physics3D.min.js"), 
loadLib("libs/min/sdk.wx.min.js"), 
loadLib("js/main.js");
